### ISSUE TITLE
Create function check palindrome

### ISSUE THREAD

**Issue by bambilitaz** [cnc-solution/bong-and-bibi#5]
create new program to check is palindrome

i have string(16) jaa : )

**Comment by bambilitaz** [comment]
@bongtrop  บ้องงงงง ทำนะเหวยยยย~

**Comment by bongtrop** [comment]
Ok, I have some problem. How to get input krab?

**Comment by bambilitaz** [comment]
How what ? i dont understand

**Comment by bongtrop** [comment]
scanf or args krub

**Comment by bambilitaz** [comment]
Args is okay ka : )
